### PR TITLE
Remove dependency on grafana codebase.

### PR DESCRIPTION
**Pull request by avaskys**
There was one struct getting pulled in from grafana. Which in
turn pulls in a slew of dependencies.

### CODE REVIEW

**Comment by keunwoo** [comment]
There is one downside, which is that this has to be kept in sync manually with the grafana API struct. I have a couple of questions:
1. What do you think the likelihood is that, over time, this API client package will start using more structs in dtos?
2. Does it make sense to ask the Grafana team to factor their API wire protocol definitions into a separate repository? I see that hashicorp has also forked a copy of the structs in dtos, probably for a similar reason:
   https://github.com/hashicorp/terraform/tree/master/vendor/github.com/grafana/grafana/pkg/api/dtos 
3. (off-topic) Do you have any idea what dtos stands for? Doritos?

**Comment by keunwoo** [comment]
BTW we don't necessarily have to block this change behind figuring out the long-term solution. I'm OK with merging this and getting dtos factored out as a separate issue.

**Comment by avaskys** [comment]
> There is one downside, which is that this has to be kept in sync manually with the grafana API struct.

Yeah. I agree that that's a downside.

> What do you think the likelihood is that, over time, this API client package will start using more structs in dtos?

Actually, there are other structs in this repo that should really already be references to the dtos package. DashboardMeta in dashboard.go, for example. But for whatever reason, the implementer decided to copy them into this client library.

> Does it make sense to ask the Grafana team to factor their API wire protocol definitions into a separate repository?

It doesn't even need to be in a separate repository, they would just need to restructure things so that dtos isn't bringing packages with a whole bunch of external dependencies. I started going down the path of bringing in every submodule that dtos needs (but shouldn't need), and I decided this change was the easier solution. At any rate, I've filed this: https://github.com/grafana/grafana/issues/5535

> Do you have any idea what dtos stands for? Doritos?

Mmmm, Doritos..... But yeah, I think it's this: https://en.wikipedia.org/wiki/Data_transfer_object

**Comment by keunwoo** [comment]
OK, I just wanted to make sure we made some noise to put grafana on a path to make dtos less unwieldy.

LGTM for merge.

**Pull request merged**
